apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: job
  annotations:
    workflows.argoproj.io/description: |
      This workflows builds and tests a project using a job. 
      
      It demonstrates:
      
      * Cache restore and store.
      * Publishing test reports.
spec:
  arguments:
    parameters:
      - name: branch
        value: master

  entrypoint: main

  activeDeadlineSeconds: 300

  templates:
    - name: main
      inputs:
        artifacts:
          - name: go-mod-cache
            path: /go/pkg/mod
            optional: true
            s3:
              key: "github.com/golang/examples/{{workflow.parameters.branch}}/go-mod-cache"
          - name: go-cache
            path: /root/.cache/go-build
            optional: true
            s3:
              key: "github.com/golang/examples/{{workflow.parameters.branch}}/go-cache"
      job:
        image: golang
        workingDir: /go/src/github.com/golang/example
        steps:
          - name: clone
            run: git clone -v -b "{{workflow.parameters.branch}}" --single-branch --depth 1 https://github.com/golang/example.git .
          - name: deps
            run: go mod download
          - name: build
            run: go build ./...
          - name: test
            run: |
              go test -v ./... 2>&1 > test.out
              exit 1 # force failure
          - name: test-report
            if: always()
            run: |
              go install github.com/jstemmer/go-junit-report@latest
              go install github.com/alexec/junit2html@latest
          
              cat test.out | go-junit-report | junit2html > test-report.html
      outputs:
        artifacts:
          - name: go-mod-cache
            path: /go/pkg/mod
            optional: true
            s3:
              key: "github.com/golang/examples/{{workflow.parameters.branch}}/go-mod-cache"
          - name: go-cache
            path: /root/.cache/go-build
            optional: true
            s3:
              key: "github.com/golang/examples/{{workflow.parameters.branch}}/go-cache"
          - name: test-report
            path: /go/src/github.com/golang/example/test-report.html
            archive:
              none: { }
            s3:
              key: "{{workflow.parameters.branch}}/test-report.html"
